apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: bulletin
  region: us-east-2
vpc:
  subnets:
    private:
      us-east-2a:
        id: !Sub ${EnvironmentName}-PRI1-SN
      us-east-2b:
        id: !Sub ${EnvironmentName}-PRI2-SN
nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
